version: "3.8"
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alexsnik/infra_web_actions:latest
    restart: always
    volumes:
      - "static_value:/app/static/"
      - "media_value:/app/media/"
    depends_on:
      - db
    env_file:
      - ./.env
  certbot:
    image: certbot/certbot:latest
    volumes:
      - "./certbot/www/:/var/www/certbot/"
      - "./certbot/conf/:/etc/letsencrypt/"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./certbot/conf:/etc/letsencrypt/
      - ./certbot/www:/var/www/certbot/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
      - certbot
volumes:
  static_value:
  media_value: